### ISSUE TITLE
Support Microsoft Git Provider

### ISSUE THREAD

**Issue by prodrive** [ceztko/SccAutoSwitcher#1]
Any chance you could add support for the Microsoft Git Provider built into VS2013?

**Comment by ceztko** [comment]
Microsoft Git Provider should be already supported and you can verify the switch is correctly done by checking "Options -> Source Control". I just tried it: differently from others provider the switch doesn't pop-up related windows. In case it doesn't work for you please tell me what happens when you:
- Switch manually to a diffent provider (ex. Team Foundation);
- Initialize a empty git repository on any solution;
- Close and reload the solution;
- Go to "Options -> Source Control" and discover the loaded provider.

**Comment by prodrive** [comment]
I'm not sure what I did wrong the first time. I retried using the process you posted above, and it's been working great ever since. Thanks for a great plugin!
